#!/bin/bash
# Deploy Artemis II to Firebase - Complete Setup Guide

echo "=== Firebase Deployment Setup for Artemis II Mission Control ==="
echo ""
echo "Your Firebase project is configured in .firebaserc:"
echo "  Project: artemisii"
echo ""
echo "Step 1: Authenticate with Firebase"
echo "Run this command to open the browser login:"
echo ""
echo "  firebase login"
echo ""
echo "Step 2: After logging in, deploy with:"
echo ""
echo "  firebase deploy"
echo ""
echo "Step 3: View your live app:"
echo ""
echo "  https://artemisii.web.app"
echo ""
echo "Alternative: Deploy using this one-liner:"
echo ""
echo "  firebase login && firebase deploy"
echo ""
