#!/bin/bash
# Firebase Deployment Instructions for Artemis II Mission Control

echo "=== Artemis II Mission Control - Firebase Deployment ==="
echo ""
echo "To deploy this app to Firebase, follow these steps:"
echo ""
echo "1. Install Firebase CLI globally (if not already installed):"
echo "   npm install -g firebase-tools"
echo ""
echo "2. Login to Firebase:"
echo "   firebase login"
echo "   (This will open a browser for authentication with your Google account)"
echo ""
echo "3. Deploy the app:"
echo "   cd d:\artemis2"
echo "   firebase deploy"
echo ""
echo "4. Your app will be deployed to:"
echo "   https://artemisii.firebaseapp.com"
echo ""
echo "Firebase Configuration:"
echo "- Project ID: artemisii"
echo "- Hosting URL: https://artemisii.web.app"
echo ""
echo "The deployment is configured in firebase.json to serve:"
echo "- Public directory: . (root directory)"
echo "- Main file: artemis-mission-control_17.html"
echo ""
